# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db43427135c1937369e89bffafbc3ccd1eb8319015854e138ec8f48dc81c748fab2adbdefc704c9674ec0efc63051ae7fe59675f31f4f208d5d6c762b3f5080a

test:
  secret_key_base: a0750cfb5c1c9d84c14a2d5c44b5776e8ed04a12fd4a638b930702bac9698487db98f9a968def26f507398ca3581ef48c2185bce59514727acac82463dcd7302

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
